### ISSUE TITLE
Icons for custom integration

### ISSUE THREAD

**Issue by MichaelST01** [dupondje/nrgkick-ha#1]
I resized the NRGKick icons to be used in [](https://github.com/home-assistant/brands). 

![Nrgkick_icon_256](https://github.com/dupondje/nrgkick-ha/assets/107936185/80d361b9-0060-43ef-899d-cb6e6ba11cef)
![Nrgkick_icon_512](https://github.com/dupondje/nrgkick-ha/assets/107936185/a41966ce-eb38-4bcf-81d0-c5bc873a8b0f)

**Comment by dupondje** [comment]
This needs to be a PR on https://github.com/home-assistant/brands.
As that is the repository where all the logo's are.
Feel free to create one there :)

**Comment by MichaelST01** [comment]
I added the logo there.
It is available as icon with 
![](https://brands.home-assistant.io/_/nrgkick/icon.png)

**Comment by dupondje** [comment]
Nice thanks!
