### ISSUE TITLE
Cannot setup integration

### ISSUE THREAD

**Issue by RutgerBeyen** [dupondje/nrgkick-ha#16]
After adding the code to the custom_components folder, the setup in HA fails when trying to the integration:

![image](https://github.com/dupondje/nrgkick-ha/assets/21310973/4601ce48-4149-46c1-8f9e-c49d3b7a0b8a)

**Comment by dupondje** [comment]
You will need to post your logs or some more info.
As this really gives no info :)

**Comment by RutgerBeyen** [comment]
Solved: I was connected to HA remotely, through Nginx. Seems this didn't work. When directly connected on the same LAN the setup succeeded.
