### ISSUE TITLE
NRGKick Status Online/Offline

### ISSUE THREAD

**Issue by aichingerk** [dupondje/nrgkick-ha#18]
How can I detect that the charger is connected to the main power supply and has a connection to the Home Assistant? 

I disconnected the NRG Kick from the main power for testing and all values are still available in the Home Assistant.
![image](https://github.com/dupondje/nrgkick-ha/assets/82718567/8e97cf30-0723-49f5-9494-64fb7f1b73a3)

It has happened a few times that the charger has lost the connection to the WIFI and the car was not charged at night because I hadn't noticed it.

How could I check or query this?

**Comment by dupondje** [comment]
When it can't update the data, it should return an exception to HA:
https://github.com/dupondje/nrgkick-ha/blob/main/custom_components/nrgkick/coordinator.py#L92

Feel free to debug this futher, but this should work.
I don't know exactly what HA does when the coordinator returns an exception like above.
