### ISSUE TITLE
Configure Integration

### ISSUE THREAD

**Issue by aichingerk** [dupondje/nrgkick-ha#2]
Hi,
can you please update the readme, because you have now also entered a pin where the uuid is no longer needed and communication can be established.
![image](https://github.com/dupondje/nrgkick-ha/assets/82718567/c9e1ce32-f74e-4d3b-bcdb-cf693a6d2abb)

I have been waiting for this feature from the manufacturer for 1.5 years and then suddenly I found yours. A great job, thank you

**Comment by Sachse0815** [comment]
Go to the app, sett the pin new ( I set it back to the serials) and it works great for me
