### ISSUE TITLE
New API for NRGKick

### ISSUE THREAD

**Issue by xlazam01** [dupondje/nrgkick-ha#20]
There is a new API available for NRGkick Gen2 chargers.

ModbusTCP
JSON

Documetation is here: https://www.nrgkick.com/wp-content/uploads/2024/06/website_simulate.html

I tested the API over JSON with "rest" and "rest_command" features and it works - I would be awesome to intergrate this API into your solution

**Comment by dupondje** [comment]
Yea, I have it also, and need to play with it.
This integration needs to be switched to use the JSON API, but just need to find the time to implement it.

**Comment by dupondje** [comment]
https://github.com/dupondje/nrgkick-ha/commits/feat/api/

Feel free to test it :)
@fano0001: Care to translate the new strings file in German ? :)

**Comment by fano0001** [comment]
@dupondje yes, will translate it after my vecations

**Comment by mgrn0** [comment]
@dupondje i can also try to help with that if you want.

**Comment by dupondje** [comment]
@mgrn0 : If you want :)
My german isn't great, and I don't want to push an update which breaks the german translation.

**Comment by fano0001** [comment]
@dupondje  if you merge your feature branch in the main i can make the translation in my forked project an will create a pull request.

I found no option to sync my fork with your feature branch and i have no write access to your branch directly.

**Comment by fano0001** [comment]
Created a PR with the new translation file
https://github.com/dupondje/nrgkick-ha/pull/21

**Comment by dupondje** [comment]
Pushed new version that uses the new API :)

**Comment by cy-bertrand** [comment]
Hi @dupondje ,
first : You're making great work and thanks for that !

Question : 
Can't we keep as well the old way to connect via cloud as an option ? / or on another repo on HACS ?

(My NRGKick is not yet updated + what about Sim connected device (not a fix ip) )

Many thanks,
