### ISSUE TITLE
Current adjustment only with fixed numbers

### ISSUE THREAD

**Issue by SchoergPet** [dupondje/nrgkick-ha#24]
First of all, the new integration works fine now and is much quicker (readings/control sensitivity) than before.

The only thing I miss is a possibility to set the current value (load rate [A])  with a calculated value via number helper or template.

Would be great to have that if possible.
Or is there a possiblity which a have'nt found

**Comment by SchoergPet** [comment]
Ok. I'll try. Thank you!!

**Comment by dupondje** [comment]
@SchoergPet : Does this work? If so, please close the issue :)

**Comment by SchoergPet** [comment]
oh. Yes it works. Thanks!
