### ISSUE TITLE
Add german translation

### ISSUE THREAD

**Issue by fano0001** [dupondje/nrgkick-ha#4]
Hi i would to provide a german translation to your project.

Maybe you grant me contributor access, so that i can create a branch and a Merge Request for my translation file.

**Comment by dupondje** [comment]
Hi,

You can just fork the repository and add your translation and then do a PR :)
I'll be happy to review it!

**Comment by fano0001** [comment]
Added a PR from my fork
https://github.com/dupondje/nrgkick-ha/pull/5

**Comment by dupondje** [comment]
Merged
