### ISSUE TITLE
NRGKick does not respond

### ISSUE THREAD

**Issue by SchoergPet** [dupondje/nrgkick-ha#9]
Hello dupondje!
I'm rather new in Homeassistant. I hope it's just a "newbe-mistake" and you can help me.
I have installed NRGKick integration via HACS several times, but it seems that I can't get my NRGKick (new WiFi and BLT version) connected. I'm sure to have the correct IP address, and PIN. I do not have the UUID, but I used the7 digit serial number as described.
During installation it says 1 device found... but then I cannot read voltage or any other parameter nor start/stop loading my car.

It looks like this:
![HACS - NRGKickInt](https://github.com/dupondje/nrgkick-ha/assets/149110925/0aec5bd6-b85e-4799-afc4-f0be1a16dd8f)

Any help really appreciated!

BR Peter

**Comment by dupondje** [comment]
Hi,

That's weird. The App gives correct information?
Have you checked the HomeAssistant logs? Anything showing up there for the nrgkick integration?

Cause it seems like HA can connect to the NRGKick (otherwise it would give no devices and give unavailable for the sensors), but it receives no data on it somehow ...

**Comment by SchoergPet** [comment]
The app works correct and shows actual data
![Screenshot_20240205-154321](https://github.com/dupondje/nrgkick-ha/assets/149110925/3139bdb1-fc8d-4f61-92e4-67c8cd8c40c1)

Anoher effect I found is, when I use one of the switches chargeing limit / charging state and set it zo ON... after 1 second it switches back to OFF


No additional logs found in logbook :-/

**Comment by dupondje** [comment]
Strange.
How are you running HA ? In a container? On a Linux system?

What's the IP of the NRGKick? I might be able to send you a linux/windows binary which gives you all the responses of the NRGKick (if you run it on the same network), might be useful to see if it actually returns any data.

Or ofcourse if you could give me somehow access to the system running HA, then I can debug further :)
Feel free to send me an email if you don't want to share the info here!

**Comment by SchoergPet** [comment]
I'm running HA OS 11.5 on a Raspberry PI4. 
How can I find out your email address ?

**Comment by maivorbim** [comment]
Hello, I am having the same issue, is there any way we can investigate further? I have also tried with the index.html file and when I press kick I am getting Failed to kick. Please check your values.

**Comment by dupondje** [comment]
Indeed, as the serial number derived access code is the default. But if you set a pin, that is the one you should use indeed. Might need to clarify that somewhere :)
Enjoy!
